@startuml

class GamesPlatform {
    +ListOfPlayers
    +showPlayersList()
    +createPlayer()
    +PlayGame(Game game)
    +Game[] games
    +ShowMenu()
}

package game {
    abstract class Game {
        +NumberOfPlayers
        {abstract}Introduction()
        +Resume()
        {abstract}Execute()
        {abstract}AssignRoles()
        +SelectPlayers()
    }
    class TicTacToe {

    }
    class HangMan {
        
    }
    interface HangManPlayer{

    }

    interface TicTacToePlayer {

    }
}

package player {
    abstract class Player {
        +IdPlayer int
        +PlayerName String
        +ThrowDice()
    }
    class ListOfPlayers {
        
        +Player [] players
        +CreatePlayer()
        +GetPlayer()
    }
    class Bot {

    }
    class Human {

    }
}

GamesPlatform *-- "2" Game
GamesPlatform *-- ListOfPlayers

Game <|-- TicTacToe
Game <|-- HangMan
Player <|-- Bot
Player <|-- Human
Player ..|>HangManPlayer
Player ..|>TicTacToePlayer

Game ..> ListOfPlayers

ListOfPlayers *-- Player

TicTacToe *-- TicTacToePlayer
HangMan *-- HangManPlayer

@enduml